server:
  port: 8080
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/cliente/**
        - id: ms-procesamiento-pedidos-service
          uri: lb://ms-procesamiento-pedidos-service
          predicates:
            - Path=/pedido/**
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/producto/**
        - id: categoria-service
          uri: lb://categoria-service
          predicates:
            - Path=/categoria/**
        - id: ms-carrito-service
          uri: lb://ms-carrito-service
          predicates:
            - Path=/carrito/**

